version: "3.8"

services:
  app:
    image: kelortondo/sdc-qa:server
    ports:
      - 3000:3000
    depends_on:
      - mongo
  mongo:
    image: kelortondo/sdc-qa:db
    ports:
      - 27017:27017
    volumes:
      - /usr/local/var/mongodb:/data/db
